using HarmonyLib;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Logging;

namespace CultLeaderMod.CultLeaderModCode.Patches;

[HarmonyPatch]
public static class LocInjectPatch
{
    [HarmonyPatch(typeof(LocManager), "SetLanguageInternal")]
    [HarmonyPostfix]
    private static void Postfix(string language, Dictionary<string, LocTable> tables)
    {
        if (tables == null) return;

        Log.Info($"[CultLeaderMod] LocInjectPatch firing for language={language}");

        if (tables.TryGetValue("characters", out var charTable))
        {
            charTable.MergeWith(new Dictionary<string, string>
            {
                ["CULT_LEADER_MOD_CHARACTER_CULT_LEADER_MOD_CHARACTER.title"] = "教主",
                ["CULT_LEADER_MOD_CHARACTER_CULT_LEADER_MOD_CHARACTER.titleObject"] = "教主",
                ["CULT_LEADER_MOD_CHARACTER_CULT_LEADER_MOD_CHARACTER.possessiveAdjective"] = "教主的",
                ["CULT_LEADER_MOD_CHARACTER_CULT_LEADER_MOD_CHARACTER.pronounObject"] = "TA",
                ["CULT_LEADER_MOD_CHARACTER_CULT_LEADER_MOD_CHARACTER.pronounPossessive"] = "TA的",
                ["CULT_LEADER_MOD_CHARACTER_CULT_LEADER_MOD_CHARACTER.pronounSubject"] = "TA",
                ["CULT_LEADER_MOD_CHARACTER_CULT_LEADER_MOD_CHARACTER.description"] = "掌控使徒之力的神秘教主。",
            });
            Log.Info("[CultLeaderMod] Character localization injected");
        }

        if (tables.TryGetValue("cards", out var cardsTable))
        {
            cardsTable.MergeWith(new Dictionary<string, string>
            {
                ["CULT_LEADER_MOD_CARD_CULT_LEADER_STRIKE.title"] = "打击",
                ["CULT_LEADER_MOD_CARD_CULT_LEADER_STRIKE.description"] = "造成{Damage:diff()}点伤害。",
                ["CULT_LEADER_MOD_CARD_CULT_LEADER_DEFEND.title"] = "防御",
                ["CULT_LEADER_MOD_CARD_CULT_LEADER_DEFEND.description"] = "获得{Block:diff()}点格挡。",

                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_PURE_CARD.title"] = "纯粹使徒UP",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_PURE_CARD.description"] = "纯粹性格使徒的出现概率提升。",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_CALM_CARD.title"] = "冷静使徒UP",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_CALM_CARD.description"] = "冷静性格使徒的出现概率提升。",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_FRENZY_CARD.title"] = "狂热使徒UP",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_FRENZY_CARD.description"] = "狂热性格使徒的出现概率提升。",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_LIVELY_CARD.title"] = "活泼使徒UP",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_LIVELY_CARD.description"] = "活泼性格使徒的出现概率提升。",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_MELANCHOLY_CARD.title"] = "忧郁使徒UP",
                ["CULT_LEADER_MOD_CARD_PERSONALITY_SELECT_MELANCHOLY_CARD.description"] = "忧郁性格使徒的出现概率提升。",
                ["CULT_LEADER_MOD_CARD_TEST_RAINBOW_CARD.title"] = "循环",
                ["CULT_LEADER_MOD_CARD_TEST_RAINBOW_CARD.description"] = "获得1层再生、覆甲、活力、计划妥当和苦痛。{NL}抽1张牌。",
                ["CULT_LEADER_MOD_CARD_CULT_LEADER_MANIFESTATION_CARD.title"] = "教主的权现",
                ["CULT_LEADER_MOD_CARD_CULT_LEADER_MANIFESTATION_CARD.description"] = "获得1层教主的权能。",
                ["CULT_LEADER_MOD_CARD_ELDER_FORM_CARD.title"] = "埃尔德形态",
                ["CULT_LEADER_MOD_CARD_ELDER_FORM_CARD.description"] = "获得1层教主的权能，此效果触发5次。",
                ["CULT_LEADER_MOD_CARD_TEST_ADD_APOSTLE_CARDS.title"] = "TEST",
                ["CULT_LEADER_MOD_CARD_TEST_ADD_APOSTLE_CARDS.description"] = "向弃牌堆中添加测试卡牌。",

                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_01.title"] = "魔力乱打",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_01.description"] = "移除所有再生和生命本源，每移除一层对随机敌人造成10点伤害\n升级：升级后每次伤害变为13",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_02.title"] = "要来少女的身边吗？",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_02.description"] = "获得25格挡和4再生\n升级：升级后30格挡和5再生",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_03.title"] = "围猎",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_03.description"] = "造成{Damage:diff()}点伤害3次。如果目标生命值低于你的最大生命值，则再发动一次。{IfUpgraded:show:\n费用由2变为1。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_04.title"] = "休假中潜逃",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_04.description"] = "获得3再生，每有一层再生或者生命本源获得8点格挡\n升级：升级后4再生和10格挡",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_05.title"] = "最强的收集品",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_05.description"] = "造成{Damage:diff()}点伤害。如果再生和生命本源总层数超过{StackThreshold}，眩晕目标以外的其他敌人。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_06.title"] = "南瓜魔术",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_06.description"] = "获得2再生和5格挡\n升级：升级后移除消耗",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_07.title"] = "我来保护你",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_07.description"] = "获得5再生和10格挡，抽1张牌\n升级：升级改为抽2",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_08.title"] = "调皮的笑容",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_08.description"] = "给予目标2层虚弱。目标每有一种减益状态，获得1层再生。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_09.title"] = "玛戈玛恢复",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_09.description"] = "如果再生不足5层，则获得3层再生；如果超过5层，则立即触发3次再生，并抽2张牌\n升级：升级后移除消耗",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_10.title"] = "魔女档案",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_10.description"] = "获得等同于当前战斗牌堆中纯粹使徒牌数量的再生。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_11.title"] = "谢绝(Non grata)",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_11.description"] = "造成5点伤害，如果再生或生命本源层数不低于2，减少2层并再造成8点伤害\n升级：升级后伤害变为8和10",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_12.title"] = "接受水的洗礼吧！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_12.description"] = "立即触发2次再生或生命本源，根据回复生命值的量对全体敌人造成伤害\n升级：升级后变为立即触发3次",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_13.title"] = "汁液泵机发射！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_13.description"] = "获得1层再生。抽1张牌。升级后获得能量。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_14.title"] = "钻石穿刺",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_14.description"] = "对全体敌人造成10+再生和生命本源层数的伤害。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_15.title"] = "快躲开啊啊!!!噫…?",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_15.description"] = "对全体敌人造成50点伤害。升级后65点。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_16.title"] = "欧珀粉",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_16.description"] = "每有一层再生和生命本源，获得1点格挡\n升级：升级后变为每层获得2点格挡",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_17.title"] = "远程充电",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_17.description"] = "获得1层再生。抽1张牌。升级后获得能量。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_18.title"] = "突发惊吓",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_18.description"] = "获得1层缓冲。若再生和生命本源合计不低于5层，再获得1层缓冲。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_19.title"] = "基础黑客攻击",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_19.description"] = "造成当前再生层数的伤害，本回合内使其失去当前再生层数的力量\n升级：升级后费用变为0",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_20.title"] = "帮帮我，朋友们！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_20.description"] = "每有一层再生和生命本源获得1点临时力量，之后对全体敌人造成10点伤害\n升级：造成10点伤害变为13点伤害",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_21.title"] = "清晰的界限",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_21.description"] = "抽1张牌，触发1次再生\n升级：升级后抽牌数和再生的触发次数变为2",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_22.title"] = "看~看看我~",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_22.description"] = "从目标敌人夺取10临时最大生命值\n升级：升级后夺取最大生命值变为15",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_23.title"] = "投降！投降了啦......",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_23.description"] = "自身和所有敌人本回合-15力量\n升级：升级后-15力量变为-20力量",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_24.title"] = "铁锹击",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_24.description"] = "造成最大生命值20%的伤害。{IfUpgraded:show:\n升级后变为25%。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_25.title"] = "黄瓜油",
                ["CULT_LEADER_MOD_CARD_APOSTLE_PURE_25.description"] = "获得{RegenAmt}层再生。\n抽{DrawAmt:diff()}张牌。",

                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_01.title"] = "雪花蝶舞",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_01.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_02.title"] = "百帕斯卡 挥棒!",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_02.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_03.title"] = "战术无人机 MK-2",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_03.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_04.title"] = "战术卫星助阵",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_04.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_05.title"] = "咿 呀 蜜瓜吖~",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_05.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_06.title"] = "刺痛的门卫",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_06.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_07.title"] = "锗玉电热毯",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_07.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_08.title"] = "魔法：圆舞切割",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_08.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_09.title"] = "泳池候选地",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_09.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_10.title"] = "限定贴纸!",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_10.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_11.title"] = "界限模糊",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_11.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_12.title"] = "说闲话的玩偶",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_12.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_13.title"] = "雪雾",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_13.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_14.title"] = "新产品试用",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_14.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_15.title"] = "里科塔 全套餐",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_15.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_16.title"] = "粉碎",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_16.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_17.title"] = "修剪枝条",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_17.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_18.title"] = "蜂蜜炸弹",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_18.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_19.title"] = "墨水洗礼",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_19.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_20.title"] = "心中的珍珠",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_20.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_21.title"] = "超天才的演出",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_21.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_22.title"] = "摇曳幽烛",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_22.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_23.title"] = "脑机连接开始",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_23.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_24.title"] = "给我吃薄荷！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_24.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_25.title"] = "XG-激光",
                ["CULT_LEADER_MOD_CARD_APOSTLE_CALM_25.description"] = "获得1层覆甲。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",

                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_01.title"] = "小小塞巴斯蒂安",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_01.description"] = "获得1层活力。抽1张牌。升级后获得能量。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_02.title"] = "真正的治愈",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_02.description"] = "造成14点伤害。升级后16点。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_03.title"] = "杀戮时刻",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_03.description"] = "对全体敌人造成7点伤害，获得2活力\n升级：对全体敌人造成9点伤害，获得3活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_04.title"] = "世界树启示录",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_04.description"] = "获得2活力，之后获得当前活力2倍的格挡\n升级：当前活力2倍的格挡变为3倍",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_05.title"] = "Money Gun",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_05.description"] = "造成5点伤害。消耗。升级后8点。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_06.title"] = "猩红之雨",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_06.description"] = "对所有敌人造成6点伤害2次\n升级：对所有敌人造成9点伤害2次",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_07.title"] = "阿卡那",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_07.description"] = "从“对随机敌人造成6点伤害”“获得3活力”“获得5格挡”中随机发动一个，触发2次\n升级：触发2次改为触发3次",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_08.title"] = "淬火击",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_08.description"] = "造成16点伤害，活力对此卡产生3倍效果\n升级：造成18点伤害，活力对此卡产生5倍效果",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_09.title"] = "鹿派斩击",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_09.description"] = "获得1层活力。抽1张牌。升级后获得能量。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_10.title"] = "偏向性解说",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_10.description"] = "一名敌人本回合减少5力量，自身获得5活力\n升级：一名敌人本回合减少7力量，自身获得7活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_11.title"] = "螺旋钻头充能",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_11.description"] = "获得12活力\n升级：获得18活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_12.title"] = "被混沌勾引",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_12.description"] = "造成8点伤害，若本次攻击消耗了5层以上的活力，则获得5活力\n升级：造成10点伤害，若本次攻击消耗了4层以上的活力，则获得6活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_13.title"] = "向妖精王国敬礼",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_13.description"] = "获得6点格挡，获得3活力\n升级：获得8点格挡，获得5活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_14.title"] = "收款的时间到了！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_14.description"] = "每有一个敌人，获得10金币和3活力\n升级：每有一个敌人，获得15金币和5活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_15.title"] = "时间中断",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_15.description"] = "获得15层活力。目标敌人本回合减少15点力量。消耗。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_16.title"] = "喜欢喝彩的演员",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_16.description"] = "获得8点格挡，抽1张牌\n升级：升级后添加：获得5活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_17.title"] = "潜入采访中！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_17.description"] = "获得1层活力。抽1张牌。升级后获得能量。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_18.title"] = "纯真☆光束",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_18.description"] = "对所有敌人造成10点伤害，活力对此卡产生2倍效果\n升级：对所有敌人造成15点伤害，活力对此卡产生3倍效果",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_19.title"] = "向前迈进的决心",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_19.description"] = "一次性触发每5层活力，获得2层活力\n升级：一次性触发每4层活力，获得2层活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_20.title"] = "要来见少女吗？",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_20.description"] = "获得1层活力。抽1张牌。升级后获得能量。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_21.title"] = "古老的誓约",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_21.description"] = "获得4覆甲，本回合失去10力量，下回合获得10活力\n升级：6覆甲/15力量/15活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_22.title"] = "机器人矩阵",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_22.description"] = "获得8点格挡，当前活力层数不少于5，抽一张牌，不少于20，获得2点能量\n升级：获得10点格挡，当前活力层数不少于4，抽一张牌，不少于16，获得2点能量",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_23.title"] = "那个收藏品是我的",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_23.description"] = "造成5点伤害。",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_24.title"] = "篝火",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_24.description"] = "回合开始时获得3活力\n升级：3活力变为5活力",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_25.title"] = "手里剑要飞了！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_25.description"] = "本回合每消耗3活力，获得1格挡\n升级：获得1格挡变为2格挡",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_26.title"] = "发射！啊biu~",
                ["CULT_LEADER_MOD_CARD_APOSTLE_FRENZY_26.description"] = "造成8点伤害。消耗。",

                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_01.title"] = "呱呱雨~",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_01.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_02.title"] = "再来一次!",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_02.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_03.title"] = "卢波流 神速斩",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_03.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_04.title"] = "强力一击",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_04.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_05.title"] = "黄油飞射",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_05.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_06.title"] = "音速斩击",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_06.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_07.title"] = "全心全意",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_07.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_08.title"] = "戏剧性演出",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_08.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_09.title"] = "我想听你讲个故事",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_09.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_10.title"] = "总有一天会发生的事",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_10.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_11.title"] = "堂堂正正的舞蹈对决",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_11.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_12.title"] = "警戒线上的幽灵",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_12.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_13.title"] = "调整",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_13.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_14.title"] = "干净的话就没活干了！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_14.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_15.title"] = "梢杀 松鼠雷电",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_15.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_16.title"] = "速邦配送",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_16.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_17.title"] = "次元裂缝",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_17.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_18.title"] = "圣裁宣告",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_18.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_19.title"] = "充满魄力的新秀",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_19.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_20.title"] = "魔道学者之路",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_20.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_21.title"] = "开核桃大师",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_21.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_22.title"] = "幸福的bee",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_22.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_23.title"] = "蜂蜜鱼~哈姆!",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_23.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_24.title"] = "炸弹来啦~",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_24.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_25.title"] = "胡萝卜治愈",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_25.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_26.title"] = "DX-炮弹",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_26.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_27.title"] = "噶哦哦！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_LIVELY_27.description"] = "获得1层计划妥当。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",

                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_01.title"] = "软乎乎Time",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_01.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_02.title"] = "魔.弹.の.射.手",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_02.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_03.title"] = "土豆番薯!",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_03.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_04.title"] = "内向人斩切",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_04.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_05.title"] = "侧斩",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_05.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_06.title"] = "面包流星",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_06.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_07.title"] = "芬多精波动",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_07.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_08.title"] = "通械术",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_08.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_09.title"] = "魔力喷发",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_09.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_10.title"] = "炸猪排市长，洛涅！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_10.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_11.title"] = "强制起床装置",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_11.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_12.title"] = "水大炮炮击！！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_12.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_13.title"] = "有罪宣言",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_13.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_14.title"] = "非法豆奶",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_14.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_15.title"] = "执行教理",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_15.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_16.title"] = "堕落玫瑰",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_16.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_17.title"] = "踏光寻月",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_17.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_18.title"] = "Elen-A 超频",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_18.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_19.title"] = "Go! Go! Love Stage!",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_19.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_20.title"] = "神王zhi尊 希菲尔攻击",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_20.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_21.title"] = "请整理好书籍",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_21.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_22.title"] = "猩红收割",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_22.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_23.title"] = "Rock and Peace！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_23.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_24.title"] = "斧头会飞出去的！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_24.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_25.title"] = "啪哦哦！",
                ["CULT_LEADER_MOD_CARD_APOSTLE_MELANCHOLY_25.description"] = "获得1层苦痛。\n抽1张牌。{IfUpgraded:show:\n获得{Energy:energyIcons()}。|}",
            });
            Log.Info("[CultLeaderMod] Card localization injected");
        }

        if (tables.TryGetValue("powers", out var powersTable))
        {
            powersTable.MergeWith(new Dictionary<string, string>
            {
                ["CULT_LEADER_MOD_POWER_CULT_LEADER_AUTHORITY_POWER.title"] = "教主的权能",
                ["CULT_LEADER_MOD_POWER_CULT_LEADER_AUTHORITY_POWER.description"] = "使徒牌获得的基础buff层数额外+1（每层权能）。层数达到5时，消耗5层进入埃尔德形态。",
                ["CULT_LEADER_MOD_POWER_ELDER_FORM_POWER.title"] = "埃尔德形态",
                ["CULT_LEADER_MOD_POWER_ELDER_FORM_POWER.description"] = "所有基础buff自动转化为升级版buff。",
                ["CULT_LEADER_MOD_POWER_LIFE_ESSENCE_POWER.title"] = "生命本源",
                ["CULT_LEADER_MOD_POWER_LIFE_ESSENCE_POWER.description"] = "每层提供5点最大生命。主动触发时移除1层，并回复5点生命。",
                ["CULT_LEADER_MOD_POWER_SOLID_ICE_POWER.title"] = "固若坚冰",
                ["CULT_LEADER_MOD_POWER_SOLID_ICE_POWER.description"] = "每层使从卡牌获得的格挡+1。回合结束时获得等同于层数的格挡。主动触发时移除1层，并根据当前层数获得格挡。",
                ["CULT_LEADER_MOD_POWER_FERVOR_POWER.title"] = "狂热",
                ["CULT_LEADER_MOD_POWER_FERVOR_POWER.description"] = "每有一层，使下一张攻击牌伤害+3，并失去3点生命。每次触发只消耗1层。",
                ["CULT_LEADER_MOD_POWER_BITTER_PAIN_POWER.title"] = "苦痛",
                ["CULT_LEADER_MOD_POWER_BITTER_PAIN_POWER.description"] = "回合结束时，每有一层苦痛，对一名随机敌人随机施加1层易伤、1层虚弱、3层中毒或6层灾厄。此状态不会随回合减少。",
                ["CULT_LEADER_MOD_POWER_BITTER_PAIN_BURST_POWER.title"] = "苦痛爆发",
                ["CULT_LEADER_MOD_POWER_BITTER_PAIN_BURST_POWER.description"] = "回合结束时，每有一层苦痛爆发，对所有敌人施加1层易伤、1层虚弱、3层中毒和6层灾厄。此状态不会随回合减少。",
                ["CULT_LEADER_MOD_POWER_HAPPINESS_POWER.title"] = "幸福",
                ["CULT_LEADER_MOD_POWER_HAPPINESS_POWER.description"] = "获得幸福时，如果幸福不少于3层，则消耗3层，抽2张牌并获得1点能量。",
                ["CULT_LEADER_MOD_POWER_TEMP_MAX_HP_POWER.title"] = "临时最大生命",
                ["CULT_LEADER_MOD_POWER_TEMP_MAX_HP_POWER.description"] = "增加最大生命值。战斗结束后失去。",
                ["CULT_LEADER_MOD_POWER_BONFIRE_VIGOR_POWER.title"] = "篝火",
                ["CULT_LEADER_MOD_POWER_BONFIRE_VIGOR_POWER.description"] = "回合结束时获得等同于层数的活力。",
                ["CULT_LEADER_MOD_POWER_TEMP_STRENGTH_LOSS_POWER.title"] = "力竭",
                ["CULT_LEADER_MOD_POWER_TEMP_STRENGTH_LOSS_POWER.description"] = "回合结束时恢复等量力量。",
            });
        }

        if (tables.TryGetValue("card_keywords", out var kwTable))
        {
            kwTable.MergeWith(new Dictionary<string, string>
            {
                ["CULT_LEADER_MOD_KEYWORD_APOSTLE.title"] = "使徒牌",
                ["CULT_LEADER_MOD_KEYWORD_APOSTLE.description"] = "使徒之力凝聚的卡牌。",
                ["CULT_LEADER_MOD_KEYWORD_PURE.title"] = "纯粹",
                ["CULT_LEADER_MOD_KEYWORD_PURE.description"] = "纯粹使徒，与再生和生命之源相关。",
                ["CULT_LEADER_MOD_KEYWORD_CALM.title"] = "冷静",
                ["CULT_LEADER_MOD_KEYWORD_CALM.description"] = "冷静使徒，与覆甲和固若坚冰相关。",
                ["CULT_LEADER_MOD_KEYWORD_FRENZY.title"] = "狂热",
                ["CULT_LEADER_MOD_KEYWORD_FRENZY.description"] = "狂热使徒，与活力和狂热相关。",
                ["CULT_LEADER_MOD_KEYWORD_LIVELY.title"] = "活泼",
                ["CULT_LEADER_MOD_KEYWORD_LIVELY.description"] = "活泼使徒，与计划妥当和幸福相关。",
                ["CULT_LEADER_MOD_KEYWORD_MELANCHOLY.title"] = "忧郁",
                ["CULT_LEADER_MOD_KEYWORD_MELANCHOLY.description"] = "忧郁使徒，与苦痛和苦痛爆发相关。",
            });
            Log.Info("[CultLeaderMod] Keyword localization injected");
        }

        if (tables.TryGetValue("relics", out var relicsTable))
        {
            relicsTable.MergeWith(new Dictionary<string, string>
            {
                ["CULT_LEADER_MOD_RELIC_GUM_BLESS_RELIC.title"] = "咏春的祝福",
                ["CULT_LEADER_MOD_RELIC_GUM_BLESS_RELIC.description"] = "选择两种使徒性格，使其出现概率提升。",
                ["CULT_LEADER_MOD_RELIC_GUM_BLESS_RELIC.flavor"] = "性格UP卡池已经开启了，教主的晶叶准备好了么",
            });
            Log.Info("[CultLeaderMod] Relic localization injected");
        }

        if (tables.TryGetValue("gameplay_ui", out var guiTable))
        {
            guiTable.MergeWith(new Dictionary<string, string>
            {
                ["CULT_LEADER_PERSONALITY_SELECTION.prompt"] = "选择两种使徒性格",
                ["CULT_LEADER_PERSONALITY_SELECTION.title"] = "选择两种使徒性格",
                ["CULT_LEADER_PERSONALITY_SELECTION.description"] = "咏春的祝福正在回应你。先选择两种性格，再接受涅奥的遗物。",
            });
            Log.Info("[CultLeaderMod] Gameplay UI localization injected");
        }
    }
}


